function CC = MSER(I,isdark)

run('../library/vlfeat/toolbox/vl_setup');

minarea = 10/prod(size(I));
pattern = 2 + isdark;
%pattern = 0;
switch pattern
    case 1
    [r,f] = vl_mser(I,...
            'MinDiversity',0.7,...
            'MaxVariation',0.2,...
            'MinArea',minarea, ...
            'Delta',10) ;
    case 2
    [r,f] = vl_mser(I,...
            'MinDiversity',0.7,...
            'MaxVariation',0.2,...
            'MinArea',minarea, ...
            'BrightOnDark',1, ...
            'DarkOnBright',0 ...
            );
    case 3
    [r,f] = vl_mser(I,...
            'MinDiversity',0.7,...
            'MaxVariation',0.2,...
            'MinArea',minarea, ...
            'BrightOnDark',0, ...
            'DarkOnBright',1 ...
            );
    otherwise
        [r,f] = vl_mser(I);
end


CC = struct;
CC.Connectivity = 8;
CC.ImageSize = size(I);
CC.NumObjects = numel(r);
for i = 1:numel(r)
    CC.PixelIdxList(i) = {double(vl_erfill(I,r(i)))};
end
